"""
make_ophys_nwb.py
=================

Make the ophys NWB file (zarr) for a processed multiplane-ophys session that
has no NWB file from the AIND pipeline. The layout is the same as the AIND
processed NWB (8 plane modules, the same names, types and the
ndx-aibs-behavior-ophys lab metadata).

Sources (all verified against AIND NWB files, see --check):
  dF/F                 <plane>/dff/<plane>_dff.h5 : data (roi x time)
  events               <plane>/events/<plane>_events_oasis.h5 : events
  raw / neuropil /     <plane>/extraction/<plane>_extraction.h5 :
    corrected traces     traces/roi, traces/neuropil, traces/corrected
  image masks          extraction rois/coords (roi, y, x) + rois/data (weights)
  segmentation image   extraction cellpose/masks (label k = ROI row k-1)
  projections          <plane>/motion_correction/<plane>_{average,maximum}_projection.png / 255
  soma / dendrite      <plane>/classification/<plane>_classification.h5
  timestamps           sync vsync_2p rising edges [pair :: 4] (pair from pairK.txt)
  metadata             raw session.json, subject.json, rig.json

    python make_ophys_nwb.py --check <processed_asset_with_nwb>   # compare with AIND NWB
"""
import argparse
import datetime as dt
import glob
import json
import re
import uuid
from pathlib import Path

import h5py
import numpy as np
from dateutil import parser as dparser
from hdmf_zarr import NWBZarrIO, ZarrDataIO
from numcodecs import Blosc
from PIL import Image
from pynwb import NWBFile
from pynwb.base import Images
from pynwb.file import Subject
from pynwb.image import GrayscaleImage
from hdmf.common import ElementIdentifiers, VectorData
from pynwb.ophys import (DfOverF, Fluorescence, ImageSegmentation, OpticalChannel,
                         PlaneSegmentation, RoiResponseSeries)

DATA = Path("/root/capsule/data")
REF_FOR_TYPES = sorted(glob.glob(str(DATA / "multiplane-ophys_786297_2025-05-13_09-12-38_processed_*/*.nwb")))[0]
COMPRESSOR = Blosc(cname="zstd", clevel=5, shuffle=Blosc.SHUFFLE)
SEX = {"Male": "M", "Female": "F"}


def zio(data, chunks=None):
    return ZarrDataIO(data=data, chunks=chunks, compressor=COMPRESSOR)


def rising_edges(sync_file, line):
    """Rising-edge times (s) of one sync line (same method as analysis_utils)."""
    with h5py.File(sync_file, "r") as h:
        data = h["data"][:]
        meta = eval(h["meta"][()])
    labels = meta["line_labels"]
    bit = labels.index(line)
    b = np.bitwise_and(data[:, -1], 2 ** bit).astype(bool).astype(np.uint8)
    ch = np.ediff1d(b, to_begin=b[0])
    return data[np.where(ch == 1), 0][0] / meta["ni_daq"]["sample_rate"]


def plane_pairs(proc):
    pair = {}
    for f in sorted(proc.glob("pair*.txt")):
        k = int(re.findall(r"\d+", f.name)[0])
        for line in f.read_text().split():
            pair[Path(line).name] = k
    return pair


def build_nwbfile(proc, raw, type_map_io):
    proc, raw = Path(proc), Path(raw)
    ses = json.load(open(raw / "session.json"))
    sub = json.load(open(raw / "subject.json"))
    rig = json.load(open(raw / "rig.json"))
    fovs = {f"{f['targeted_structure']}_{f['index']}": f
            for ds in ses["data_streams"] for f in ds.get("ophys_fovs", [])}
    start = dparser.isoparse(ses["session_start_time"])
    dob = dparser.isoparse(sub["date_of_birth"]).replace(tzinfo=start.tzinfo)
    nwb = NWBFile(
        session_description="NWB file generated by AIND pipeline",
        identifier=str(uuid.uuid4()), session_start_time=start,
        session_id=raw.name, institution="Allen Institute for Neural Dynamics",
        file_create_date=[dt.datetime.now(dt.timezone.utc)],
        subject=Subject(subject_id=str(sub["subject_id"]), sex=SEX.get(sub["sex"], "U"),
                        species=sub["species"]["name"], genotype=sub.get("genotype"),
                        date_of_birth=dob, age=f"P{(start - dob).days}D", age__reference="birth"))
    device = nwb.create_device(name=ses["rig_id"], description=rig.get("rig_id", ""), manufacturer="Thorlabs")
    Meta = type_map_io.manager.type_map.get_dt_container_cls("OphysMetadataSchema", "ndx-aibs-behavior-ophys")
    sync = glob.glob(str(raw / "behavior" / "*.h5"))
    assert len(sync) == 1, sync
    vsync = rising_edges(sync[0], "vsync_2p")
    pairs = plane_pairs(proc)
    genotype = sub.get("genotype", "")

    for plane in sorted(fovs):
        f = fovs[plane]
        assert pairs[plane] == f["coupled_fov_index"], f"{plane}: pair file and session.json differ"
        scale = float(f["fov_scale_factor"])
        ip = nwb.create_imaging_plane(
            name=plane, optical_channel=OpticalChannel("TODO", "TODO", 514.0),
            description="Two-photon imaging plane a", device=device, excitation_lambda=920.0,
            imaging_rate=float(f["frame_rate"]), indicator=genotype,
            location=f"Structure: {f['targeted_structure']} Depth: {f['imaging_depth']}",
            origin_coords=[0.0, 0.0, 0.0], origin_coords_unit="micrometer",
            grid_spacing=[scale, scale], grid_spacing_unit="micrometer")
        nwb.add_lab_meta_data(Meta(name=plane, imaging_depth=str(f["imaging_depth"]),
                                   imaging_plane_group=str(f["coupled_fov_index"]),
                                   field_of_view_width=str(f["fov_width"]),
                                   field_of_view_height=str(f["fov_height"])))

        p = proc / plane
        ex = h5py.File(p / "extraction" / f"{plane}_extraction.h5", "r")
        cl = h5py.File(p / "classification" / f"{plane}_classification.h5", "r")
        dff = h5py.File(p / "dff" / f"{plane}_dff.h5", "r")["data"][:].T
        ev = h5py.File(p / "events" / f"{plane}_events_oasis.h5", "r")["events"][:].T
        n_t, n_roi = dff.shape
        ts = vsync[f["coupled_fov_index"]::4]
        assert len(ts) >= n_t, f"{plane}: {len(ts)} sync frames < {n_t} ophys frames"
        ts = ts[:n_t]

        mod = nwb.create_processing_module(plane, "")
        shape = tuple(ex["rois/shape"][:])
        masks = np.zeros(shape, np.float32)
        c = ex["rois/coords"][:]
        masks[c[0], c[1], c[2]] = ex["rois/data"][:]
        cols = [VectorData(name="is_soma", description="Soma predictions", data=cl["soma/predictions"][:]),
                VectorData(name="soma_probability", description="Soma probabilities",
                           data=cl["soma/probabilities"][:, 1]),
                VectorData(name="is_dendrite", description="Dendrite predictions", data=cl["dendrites/predictions"][:]),
                VectorData(name="dendrite_probability", description="Dendrite probabilities",
                           data=cl["dendrites/probabilities"][:, 1]),
                VectorData(name="image_mask", description="Image masks for each ROI",
                           data=zio(masks, chunks=(1,) + shape[1:]))]
        ps = PlaneSegmentation(
            name="roi_table", imaging_plane=ip, id=ElementIdentifiers(name="id", data=np.arange(n_roi)),
            columns=cols,
            description="suite2p-cellposeSuite2p's anatomical mode using either the max or mean projection")
        mod.add(ImageSegmentation(name="image_segmentation", plane_segmentations=[ps]))
        region = ps.create_roi_table_region(region=list(range(n_roi)), description="all ROIs")

        def rrs(name, data, unit):
            return RoiResponseSeries(name=name, data=zio(data, chunks=(min(n_t, 10000), min(n_roi, 64))),
                                     rois=region, unit=unit, timestamps=ts)
        ts_dff = rrs("dff_timeseries", dff, "%")
        mod.add(DfOverF(name="dff_timeseries", roi_response_series=ts_dff))
        mod.add(rrs("event_timeseries", ev, "a.u."))
        mod.add(Fluorescence(name="raw_timeseries", roi_response_series=rrs(
            "ROI_fluorescence_timeseries", ex["traces/roi"][:].T, "a.u.")))
        mod.add(rrs("neuropil_fluorescence_timeseries", ex["traces/neuropil"][:].T, "a.u."))
        mod.add(rrs("neuropil_corrected_timeseries", ex["traces/corrected"][:].T, "a.u."))

        def png(kind):
            a = np.asarray(Image.open(p / "motion_correction" / f"{plane}_{kind}_projection.png"))
            return (a / 255.0).astype(np.float32)
        mod.add(Images(name="images", images=[
            GrayscaleImage(name="average_projection", data=png("average"),
                           description="Average intensity projection of entire session"),
            GrayscaleImage(name="max_projection", data=png("maximum"),
                           description="Max intensity projection of entire session"),
            GrayscaleImage(name="segmentation_mask_image", data=ex["cellpose/masks"][:].astype(np.uint16),
                           description="Segmentation projection of entire session")]))
    return nwb


def make(proc, raw, out):
    with NWBZarrIO(REF_FOR_TYPES, "r", load_namespaces=True) as ref:
        nwb = build_nwbfile(proc, raw, ref)
        with NWBZarrIO(str(out), "w", manager=ref.manager) as io:
            io.write(nwb)
    return out


def check(proc_with_nwb, out):
    """Build from per-plane files and compare with the AIND NWB of the same session."""
    proc = DATA / proc_with_nwb
    raw = DATA / proc_with_nwb.split("_processed_")[0]
    make(proc, raw, out)
    bad = []
    with NWBZarrIO(glob.glob(str(proc / "*.nwb"))[0], "r") as a, NWBZarrIO(str(out), "r") as b:
        A, B = a.read(), b.read()
        for k in ("session_start_time", "session_id", "institution", "session_description"):
            if getattr(A, k) != getattr(B, k):
                bad.append(k)
        if A.subject.fields.keys() != B.subject.fields.keys() or any(
                str(A.subject.fields[k]) != str(B.subject.fields[k]) for k in A.subject.fields):
            bad.append(f"subject {A.subject.fields} != {B.subject.fields}")
        for p in A.processing:
            ma, mb = A.processing[p], B.processing[p]
            pairs = [("dff_timeseries/dff_timeseries", "data"), ("dff_timeseries/dff_timeseries", "timestamps"),
                     ("event_timeseries", "data"), ("raw_timeseries/ROI_fluorescence_timeseries", "data"),
                     ("neuropil_fluorescence_timeseries", "data"), ("neuropil_corrected_timeseries", "data")]
            for path, attr in pairs:
                oa, ob = ma, mb
                for part in path.split("/"):
                    oa, ob = oa[part], ob[part]
                if not np.array_equal(getattr(oa, attr)[:], getattr(ob, attr)[:]):
                    bad.append(f"{p} {path}.{attr}")
            for im in ("average_projection", "max_projection", "segmentation_mask_image"):
                if not np.array_equal(ma["images"][im].data[:], mb["images"][im].data[:]):
                    bad.append(f"{p} images/{im}")
            ra, rb = ma["image_segmentation"]["roi_table"], mb["image_segmentation"]["roi_table"]
            for col in ra.colnames:
                if not np.array_equal(ra[col].data[:], rb[col].data[:]):
                    bad.append(f"{p} roi_table.{col}")
            ia, ib = A.imaging_planes[p], B.imaging_planes[p]
            for k in ("location", "imaging_rate", "indicator", "excitation_lambda", "description"):
                if getattr(ia, k) != getattr(ib, k):
                    bad.append(f"{p} imaging_plane.{k}: {getattr(ia, k)} != {getattr(ib, k)}")
            if not np.array_equal(ia.grid_spacing[:], ib.grid_spacing[:]):
                bad.append(f"{p} grid_spacing")
            if A.lab_meta_data[p].fields != B.lab_meta_data[p].fields:
                bad.append(f"{p} lab_meta_data")
        for d in A.devices:
            if d not in B.devices or A.devices[d].description != B.devices[d].description:
                bad.append(f"device {d}")
    print("DIFFERENCES:", bad if bad else "none")
    return bad


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", help="processed asset that has an AIND NWB")
    ap.add_argument("--processed")
    ap.add_argument("--raw")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    if a.check:
        check(a.check, a.out)
    else:
        make(DATA / a.processed, DATA / a.raw, a.out)
